<?php
// --------------------------------------------------
// Autoload (Composer) + secrets (secret(), secret_js())
require_once __DIR__ . '/includes/config/load_secrets.php';
require_once __DIR__ . '/vendor/autoload.php';
// ini_set('display_errors', 1);
// ini_set('display_startup_errors', 1);
// error_reporting(E_ALL);
// $from           = $fromEmail;

	function signupemail($spram,$from){

	$to			=	$spram[5];

	$getemail	=	mysql_fetch_array(mysql_query("SELECT * from mailstable where mailid='2'"));

	$farr	=	array("[USER_FNAME]","[USER_LNAME]","[USER_EMAIL]","[USER_PASSWORD]","[USER_PHONE]");

	$aarr	=	array($spram[1],$spram[2],$spram[5],$spram[3],$spram[13]);

	$message	=	str_replace($farr,$aarr,$getemail['mailcontent']);

	  

   $headers = 'MIME-Version: 1.0' . "\r\n";

   $headers .= 'Content-type: text/html; charset=iso-8859-1' . "\r\n";

   $headers .= "From: Admin<".$from."> ". "\r\n" ;

   $subject	=	"Thank You for Register.";

    //mail( $to, $subject, $message, $headers);
    sendEmail($to, $subject, $message, $headers);

    $message = "This is an autogenerated notification email that a new user has been registered on chinesedumps.com. Below are the details.<br /><br />";
    
    if (!empty($spram[1])) {
        $message .= "User Name: " . $spram[1] . "<br />";
    }
    if (!empty($spram[13])) {
        $message .= "User Phone/Whatsapp: " . $spram[13] . "<br />";
    }
    if (!empty($spram[5])) {
        $message .= "User Email: " . $spram[5] . "<br />";
    }
    if (!empty($spram[3])) {
        $message .= "User Password: " . $spram[3] . "<br />";
    }


// 	$message = "This is an autogenerated notification email that a new user has been registered on chinesedumps.com. Below are the details.<br /><br />User Name: ".$spram[1]."<br />";

// 	$message .= "User Phone/Whatsapp: ".$spram[13]."<br /><br />";

// 	$message .= "User Email: ".$spram[5]."<br /><br />";

// 	$message .= "User Password: ".$spram[3]."<br /><br />";

    //mail( $from, "$websitename - New User Registration", $message, $headers);
    // sendEmail($from, "chinesedumps.com - New User Registration", $message, $headers);
        // $adminEmails = [
        //     'webdeveloper@nexgeno.in',
        //     'rashid.makent@gmail.com'
        // ];
        // $adminEmails = [
        //     $fromEmail,
        //     'support@chinesedumps.com'
        // ];
        // foreach ($adminEmails as $admin) {
        //     sendEmail($admin, "chinesedumps.com - New User Registration", $message, $headers);
        // }
            sendEmail('sales@chinesedumps.com', "chinesedumps.com - New User Registration", $message, $headers);
	}



	

	function forgotemail($spram,$from){

	$getemail	=	mysql_fetch_array(mysql_query("SELECT * from mailstable where mailid='1'"));

	$to			=	$spram[10];

	$farr	=	array("[USER_FNAME]","[USER_LNAME]","[USER_EMAIL]","[USER_PASSWORD]");

	$aarr	=	array($spram[1],$spram[2],$spram[5],$spram[3]);



	$message	=	str_replace($farr,$aarr,$getemail['mailcontent']);

  

   $headers  = 'MIME-Version: 1.0' . "\r\n";

   $headers .= 'Content-type: text/html; charset=iso-8859-1' . "\r\n";

   $headers .= "From: Admin<".$from."> ". "\r\n" ;

   $subject  = "Your password for ChineseDumps  Account. Thanks!";

        //mail( $to, $subject, $message, $headers);
        $res = sendEmail($to, $subject, $message, $headers);
	}

	

	function editprofileemail($spram,$from){

	$to			=	$spram[5];

	$getemail	=	mysql_fetch_array(mysql_query("SELECT * from mailstable where mailid='3'"));

	$farr	=	array("[USER_FNAME]","[USER_LNAME]","[USER_EMAIL]","[USER_PASSWORD]");

	$aarr	=	array($spram[1],$spram[2],$spram[5],$spram[3]);



	$message	=	str_replace($farr,$aarr,$getemail['mailcontent']);

  

   $headers  =  'MIME-Version: 1.0' . "\r\n";

   $headers .=  'Content-type: text/html; charset=iso-8859-1' . "\r\n";

   $headers .=  "From: Admin<".$from."> ". "\r\n" ;

   $subject	 =	"You have successfully updated your profile.";

   //mail( $to, $subject, $message, $headers);
    sendEmail( $to, $subject, $message, $headers);
	}

	

	

	function expiremailbefore7days($spram,$from){

	$to			=	$spram[1];

	$getemail	=	mysql_fetch_array(mysql_query("SELECT * from mailstable where mailid='4'"));

	$farr	=	array("[USER_FNAME]","[USER_LNAME]","[USER_EMAIL]","[USER_PRODUCT]","[USER_EXPIRE_DATE]");

	$aarr	=	array($spram[1],$spram[2],$spram[5],$spram[4],date("M j, Y",strtotime($spram[6])));



	$message	=	str_replace($farr,$aarr,$getemail['mailcontent']);

   $headers = 'MIME-Version: 1.0' . "\r\n";

   $headers .= 'Content-type: text/html; charset=iso-8859-1' . "\r\n";

   $headers .= "From: Admin<".$from."> ". "\r\n" ;

   $subject	=	"Notification to extend your product.";

    //mail( $to, $subject, $message, $headers);
    sendEmail( $to, $subject, $message, $headers);
	}	

	

	function expiremail($spram,$from){

	$to			=	$spram[1];

	$getemail	=	mysql_fetch_array(mysql_query("SELECT * from mailstable where mailid='5'"));

	$farr	=	array("[USER_FNAME]","[USER_LNAME]","[USER_EMAIL]","[USER_PRODUCT]","[USER_EXPIRE_DATE]");

	$aarr	=	array($spram[1],$spram[2],$spram[5],$spram[4],date("M j, Y",strtotime($spram[6])));



	$message	=	str_replace($farr,$aarr,$getemail['mailcontent']);

	$headers = 'MIME-Version: 1.0' . "\r\n";

	$headers .= 'Content-type: text/html; charset=iso-8859-1' . "\r\n";

	$headers .= "From: Admin<".$from."> ". "\r\n" ;

	$subject	=	"Notification to extend your product.";

    //mail( $to, $subject, $message, $headers);
    sendEmail( $to, $subject, $message, $headers);
	}	
	
	class GmailSmtpMailer {
        private $host;
        private $port;
        private $encryption;
        private $username;
        private $password;
        // private $fromEmail;
        private $fromName;
        private $timeout;
        private $heloDomain;
        private $debug = true;

        public function __construct(array $config)
        {
            // global $fromEmail;

            $this->host = isset($config['host']) ? $config['host'] : 'smtp.gmail.com';
            $this->port = isset($config['port']) ? $config['port'] : 587;
            $this->encryption = isset($config['encryption']) ? strtolower($config['encryption']) : 'tls';
            $this->username = isset($config['username']) ? $config['username'] : '';
            $this->password = isset($config['password']) ? $config['password'] : '';
            $this->fromEmail = !empty($config['from_email']) ? $config['from_email'] : $this->username;
            // $this->fromEmail = !empty($config['from_email']) ? $config['from_email'] : (!empty($fromEmail) ? $fromEmail : $this->username);
            $this->fromName = !empty($config['from_name']) ? $config['from_name'] : 'Mailer';
            $this->timeout = isset($config['timeout']) ? (int) $config['timeout'] : 30;
            $this->heloDomain = !empty($config['helo_domain']) ? $config['helo_domain'] : gethostname();
            $this->debugLog('SMTP Host: ' . $this->host);
            $this->debugLog('SMTP Port: ' . $this->port);
            $this->debugLog('Encryption: ' . $this->encryption);
            $this->debugLog('Username: ' . $this->username);
            $this->debugLog('From Email: ' . $this->fromEmail);

        }

        public function send($to, $subject, $message, $headers = '')
        {
            try {
                $socket = $this->connect();
                $this->expect($socket, [220]);

                $this->command($socket, "EHLO {$this->heloDomain}", [250]);

                if ($this->encryption === 'tls') {
                    $this->command($socket, "STARTTLS", [220]);
                    if (!stream_socket_enable_crypto($socket, true, STREAM_CRYPTO_METHOD_TLS_CLIENT)) {
                        throw new Exception('Could not start TLS encryption.');
                    }
                    $this->command($socket, "EHLO {$this->heloDomain}", [250]);
                }

                $this->command($socket, "AUTH LOGIN", [334]);
                $this->command($socket, base64_encode($this->username), [334]);
                $this->command($socket, base64_encode($this->password), [235]);

                $from = $this->sanitizeHeader($this->fromEmail);

                $toAddress = $this->sanitizeHeader($to);
                $subject = $this->sanitizeHeader($subject);

                $this->command($socket, "MAIL FROM:<{$from}>", [250]);
                $this->command($socket, "RCPT TO:<{$toAddress}>", [250, 251]);
                $this->command($socket, "DATA", [354]);

                $data = $this->buildData($toAddress, $subject, $message, $headers);
                $this->write($socket, $data . "\r\n.\r\n");
                $this->expect($socket, [250]);

                $this->command($socket, "QUIT", [221]);
                fclose($socket);
                return true;
            } catch (Exception $e) {
                error_log('Email sending failed: ' . $e->getMessage());
                return false;
            }
        }
        
        private function debugLog($message)
        {
            if ($this->debug) {
                error_log('[SMTP DEBUG] ' . $message);
            }
        }
        
        private function connect()
        {
            $sslOptions = [
                'verify_peer' => true,
                'verify_peer_name' => true,
                'allow_self_signed' => false,
            ];

            $caCandidates = array_filter([
                ini_get('curl.cainfo'),
                ini_get('openssl.cafile')
            ]);
            foreach ($caCandidates as $candidate) {
                if (is_string($candidate) && $candidate !== '' && file_exists($candidate)) {
                    $sslOptions['cafile'] = $candidate;
                    break;
                }
            }

            if (empty($sslOptions['cafile']) && $this->isLocalRequest()) {
                $sslOptions['verify_peer'] = false;
                $sslOptions['verify_peer_name'] = false;
                $sslOptions['allow_self_signed'] = true;
            }

            $scheme = $this->encryption === 'ssl' ? "ssl://" : "tcp://";
            $socket = stream_socket_client(
                $scheme . $this->host . ':' . $this->port,
                $errno,
                $errstr,
                $this->timeout,
                STREAM_CLIENT_CONNECT,
                stream_context_create([
                    'ssl' => $sslOptions
                ])
            );

            if (!$socket) {
                throw new Exception("Connection failed: {$errstr} ({$errno})");
            }

            stream_set_timeout($socket, $this->timeout);
            return $socket;
        }

        private function isLocalRequest()
        {
            $host = isset($_SERVER['HTTP_HOST']) ? strtolower((string)$_SERVER['HTTP_HOST']) : '';
            if ($host === '') {
                return false;
            }
            if ($host === 'localhost' || $host === '127.0.0.1' || $host === '::1') {
                return true;
            }
            if (strpos($host, 'localhost') !== false) {
                return true;
            }
            return false;
        }

        private function buildData($to, $subject, $message, $headers)
        {
            $lines = [];
            $lines[] = "From: {$this->fromName} <{$this->fromEmail}>";
            $lines[] = "To: <{$to}>";
            $lines[] = "Subject: {$subject}";
            $lines[] = "MIME-Version: 1.0";
            $lines[] = "Content-Type: text/html; charset=UTF-8";
            $lines[] = "Content-Transfer-Encoding: 8bit";

            $extra = $this->normalizeHeaderString($headers);
            if (!empty($extra)) {
                $lines = array_merge($lines, $extra);
            }

            $body = str_replace(["\r\n", "\r"], "\n", $message);
            $body = str_replace("\n.", "\n..", $body); // Dot-stuffing

            return implode("\r\n", $lines) . "\r\n\r\n" . $body;
        }

        private function normalizeHeaderString($headers)
        {
            if (empty($headers)) {
                return [];
            }

            $clean = [];
            $lines = preg_split('/\r\n|\r|\n/', $headers);
            foreach ($lines as $line) {
                $line = trim($line);
                if ($line === '') {
                    continue;
                }
                // Skip headers we already set above.
                $prefix = strtolower(strtok($line, ':'));
                if (in_array($prefix, ['from', 'to', 'subject', 'mime-version', 'content-type', 'content-transfer-encoding'])) {
                    continue;
                }
                $clean[] = $line;
            }
            return $clean;
        }
        
        private function command($socket, $command, array $expectedCodes)
        {
            $this->debugLog('C: ' . $command);
            $this->write($socket, $command . "\r\n");
            $this->expect($socket, $expectedCodes);
        }
        
        private function expect($socket, array $expectedCodes)
        {
            $response = $this->read($socket);
            $this->debugLog('S: ' . $response);
            $code = (int) substr($response, 0, 3);
            if (!in_array($code, $expectedCodes)) {
                throw new Exception("Unexpected SMTP response: {$response}");
            }
        }

        private function read($socket)
        {
            $data = '';
            while ($line = fgets($socket, 515)) {
                $data .= $line;
                if (strlen($line) < 4 || $line[3] === ' ') {
                    break;
                }
            }
            return trim($data);
        }

        private function write($socket, $data)
        {
            $result = fwrite($socket, $data);
            if ($result === false) {
                throw new Exception('Failed to write to SMTP socket.');
            }
        }

        private function sanitizeHeader($value)
        {
            return trim(str_replace(["\r", "\n"], '', $value));
        }
    }

	function sendEmail($to, $subject, $message, $headers) {

        static $mailer = null;

        if ($mailer === null) {
            $config = include __DIR__ . '/mail_config.php';
            $mailer = new GmailSmtpMailer($config);
        }

        return $mailer->send($to, $subject, $message, $headers);
    }
    
	/*
	function sendEmail($to, $subject, $message, $headers) {
        $config = SendinBlue\Client\Configuration::getDefaultConfiguration()->setApiKey('api-key', secret('BREVO_API_KEY', ''));
        // $config = SendinBlue\Client\Configuration::getDefaultConfiguration()->setApiKey('api-key', secret('BREVO_API_KEY', ''));
        
        $apiInstance = new SendinBlue\Client\Api\TransactionalEmailsApi(
            new GuzzleHttp\Client(),
            $config
        );
        
        $sendSmtpEmail = new \SendinBlue\Client\Model\SendSmtpEmail();
        $sendSmtpEmail['subject'] = $subject;
        $sendSmtpEmail['htmlContent'] = $message;
        $sendSmtpEmail['sender'] = array('name' => 'Chinese Dumps', 'email' => 'no-reply@chinesedumps.com');
        $sendSmtpEmail['to'] = array(
            array('email' => $to, 'name' => '-')
        );
        
        try {
            // Attempt to send the email
            $res = $apiInstance->sendTransacEmail($sendSmtpEmail);
            return $res;
        } catch (Exception $e) {
            // Log the error or handle it as needed
            error_log('Email sending failed: ' . $e->getMessage());
            return false; // or you could rethrow it or return an error object
        }
    }
    */
    

	/*function sendEmail($to, $subject, $message, $headers){*/
        /*$curl = curl_init();
        curl_setopt_array($curl, array(
          CURLOPT_URL => 'https://api.brevo.com/v3/smtp/email',
          CURLOPT_RETURNTRANSFER => true,
          CURLOPT_ENCODING => '',
          CURLOPT_MAXREDIRS => 10,
          CURLOPT_TIMEOUT => 0,
          CURLOPT_FOLLOWLOCATION => true,
          CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
          CURLOPT_CUSTOMREQUEST => 'POST',
          CURLOPT_POSTFIELDS =>'{  
           "sender":{  
              "name":"Chinese Dumps",
              "email":"no-reply@chinesedumps.com"
           },
           "to":[  
              {  
                 "email":"'.$to.'"
              }
           ],
           "subject":"'.$subject.'",
           "htmlContent":"'.$message.'"
        }',
          CURLOPT_HTTPHEADER => array(
            'accept: application/json',
            'api-key: ' . secret('BREVO_API_KEY', ''),
            'content-type: application/json'
          ),
        ));
        
        $response = curl_exec($curl);
        
        curl_close($curl);
        //echo $response;*///
     /*   
        $config = SendinBlue\Client\Configuration::getDefaultConfiguration()->setApiKey('api-key', secret('BREVO_API_KEY', ''));
        
        $apiInstance = new SendinBlue\Client\Api\TransactionalEmailsApi(
            new GuzzleHttp\Client(),
            $config
        );
        $sendSmtpEmail = new \SendinBlue\Client\Model\SendSmtpEmail();
        $sendSmtpEmail['subject'] = $subject;
        $sendSmtpEmail['htmlContent'] = $message;
        $sendSmtpEmail['sender'] = array('name' => 'Chinese Dumps', 'email' => 'no-reply@chinesedumps.com'); //info@vmwareclassmumbai.com
        $sendSmtpEmail['to'] = array(
            array('email' => $to, 'name' => '-')
        );
        //$sendSmtpEmail['replyTo'] = array('email' => $replyToEmail, 'name' => $replyToName);
        
        //trigger email
        $res = $apiInstance->sendTransacEmail($sendSmtpEmail);      
        return $res;
	}*/

?>
